import type { Metadata } from "next"
import { Archivo } from "next/font/google"
import "./globals.css"
import { Toaster } from "@/app/_components/ui/toaster"

const archivo = Archivo({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "bonfire",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="bonfire">
      <body className={archivo.className}>
        <div className="flex h-full flex-col">
          <div className="flex-1">{children}</div>
        </div>
        <Toaster />
      </body>
    </html>
  )
}
